<?php
$menu['menu910'] = array(
    array('910000', '이브알바 전용', G5_ADMIN_URL . '/jobs_register_list.php', 'evealba'),
    array('910050', '결제내역 · 매출통계', G5_ADMIN_URL . '/eve_payment_list.php', 'evealba_payment_list'),
    array('910100', '채용정보등록 관리', G5_ADMIN_URL . '/jobs_register_list.php', 'evealba_jobs_register'),
    array('910200', 'AI 콘텐츠 관리', G5_ADMIN_URL . '/jobs_ai_content_list.php', 'evealba_ai_content'),
    array('910300', '기업회원 승인관리', G5_ADMIN_URL . '/eve_enterprise_list.php', 'evealba_enterprise'),
    array('910400', '허용 업태/종목 관리', G5_ADMIN_URL . '/eve_biz_category.php', 'evealba_biz_category'),
    array('910500', '채팅 관리', G5_ADMIN_URL . '/scorepoint/scorepoint_chat_manage.php?sub_menu=910500', 'evealba_chat_admin'),
    array('910501', '공지/금칙어', G5_ADMIN_URL . '/scorepoint/scorepoint_chat_notice.php?sub_menu=910501', 'evealba_chat_notice'),
    array('910600', '채팅 밴리스트', G5_ADMIN_URL . '/scorepoint/scorepoint_chat_banlist.php?sub_menu=910600', 'evealba_chat_ban'),
    array('910700', '채팅 신고관리', G5_ADMIN_URL . '/scorepoint/scorepoint_chat_reports.php?sub_menu=910700', 'evealba_chat_report'),
    array('910800', '게시물 관리', G5_ADMIN_URL . '/scorepoint/scorepoint_board_post_manage.php?sub_menu=910800', 'evealba_board_post'),
    array('910900', 'SEO 최적화', G5_ADMIN_URL . '/scorepoint/scorepoint_seo.php?sub_menu=910900', 'evealba_seo'),
    array('910910', '점프 헬스', G5_ADMIN_URL . '/eve_jump_health.php', 'evealba_jump_health'),
    array('910920', '특수배너 관리', G5_ADMIN_URL . '/eve_special_banner.php', 'evealba_special_banner'),
    array('910930', '썸네일상점 관리', G5_ADMIN_URL . '/eve_thumb_shop.php', 'evealba_thumb_shop'),
    array('910940', '쿠폰 관리', G5_ADMIN_URL . '/eve_coupon_list.php', 'evealba_coupon'),
    array('910950', '쪽지관리', G5_ADMIN_URL . '/eve_memo_manage.php', 'evealba_memo'),
    array('910960', '매칭시스템', G5_ADMIN_URL . '/eve_matching.php', 'evealba_matching'),
    array('910970', '추천인·이력서 관리', G5_ADMIN_URL . '/eve_referral_manage.php', 'evealba_referral'),
);
