<?php
/**
 * 시·도/세부지역 정적 폴백 (005_seed_ev_region_std.sql 동일)
 * DB 비어있을 때 사용
 */
if (!defined('_GNUBOARD_')) exit;

$ev_regions_fallback = array(
    array('er_id'=>1,'er_name'=>'서울'), array('er_id'=>2,'er_name'=>'경기'), array('er_id'=>3,'er_name'=>'인천'),
    array('er_id'=>4,'er_name'=>'부산'), array('er_id'=>5,'er_name'=>'대구'), array('er_id'=>6,'er_name'=>'광주'),
    array('er_id'=>7,'er_name'=>'대전'), array('er_id'=>8,'er_name'=>'울산'), array('er_id'=>9,'er_name'=>'강원'),
    array('er_id'=>10,'er_name'=>'경남'), array('er_id'=>11,'er_name'=>'경북'), array('er_id'=>12,'er_name'=>'전남'),
    array('er_id'=>13,'er_name'=>'전북'), array('er_id'=>14,'er_name'=>'충남'), array('er_id'=>15,'er_name'=>'충북'),
    array('er_id'=>16,'er_name'=>'세종'), array('er_id'=>17,'er_name'=>'제주'));

$ev_region_details_fallback = array(
    array('erd_id'=>1,'er_id'=>1,'erd_name'=>'강남구'), array('erd_id'=>2,'er_id'=>1,'erd_name'=>'강동구'),
    array('erd_id'=>3,'er_id'=>1,'erd_name'=>'강북구'), array('erd_id'=>4,'er_id'=>1,'erd_name'=>'강서구'),
    array('erd_id'=>5,'er_id'=>1,'erd_name'=>'관악구'), array('erd_id'=>6,'er_id'=>1,'erd_name'=>'광진구'),
    array('erd_id'=>7,'er_id'=>1,'erd_name'=>'구로구'), array('erd_id'=>8,'er_id'=>1,'erd_name'=>'금천구'),
    array('erd_id'=>9,'er_id'=>1,'erd_name'=>'노원구'), array('erd_id'=>10,'er_id'=>1,'erd_name'=>'도봉구'),
    array('erd_id'=>11,'er_id'=>1,'erd_name'=>'동대문구'), array('erd_id'=>12,'er_id'=>1,'erd_name'=>'동작구'),
    array('erd_id'=>13,'er_id'=>1,'erd_name'=>'마포구'), array('erd_id'=>14,'er_id'=>1,'erd_name'=>'서대문구'),
    array('erd_id'=>15,'er_id'=>1,'erd_name'=>'서초구'), array('erd_id'=>16,'er_id'=>1,'erd_name'=>'성동구'),
    array('erd_id'=>17,'er_id'=>1,'erd_name'=>'성북구'), array('erd_id'=>18,'er_id'=>1,'erd_name'=>'송파구'),
    array('erd_id'=>19,'er_id'=>1,'erd_name'=>'양천구'), array('erd_id'=>20,'er_id'=>1,'erd_name'=>'영등포구'),
    array('erd_id'=>21,'er_id'=>1,'erd_name'=>'용산구'), array('erd_id'=>22,'er_id'=>1,'erd_name'=>'은평구'),
    array('erd_id'=>23,'er_id'=>1,'erd_name'=>'종로구'), array('erd_id'=>24,'er_id'=>1,'erd_name'=>'중구'),
    array('erd_id'=>25,'er_id'=>1,'erd_name'=>'중랑구'), array('erd_id'=>26,'er_id'=>1,'erd_name'=>'기타'),
    array('erd_id'=>27,'er_id'=>2,'erd_name'=>'가평군'), array('erd_id'=>28,'er_id'=>2,'erd_name'=>'고양시'),
    array('erd_id'=>29,'er_id'=>2,'erd_name'=>'과천시'), array('erd_id'=>30,'er_id'=>2,'erd_name'=>'광명시'),
    array('erd_id'=>31,'er_id'=>2,'erd_name'=>'광주시'), array('erd_id'=>32,'er_id'=>2,'erd_name'=>'구리시'),
    array('erd_id'=>33,'er_id'=>2,'erd_name'=>'군포시'), array('erd_id'=>34,'er_id'=>2,'erd_name'=>'김포시'),
    array('erd_id'=>35,'er_id'=>2,'erd_name'=>'남양주시'), array('erd_id'=>36,'er_id'=>2,'erd_name'=>'동두천시'),
    array('erd_id'=>37,'er_id'=>2,'erd_name'=>'부천시'), array('erd_id'=>38,'er_id'=>2,'erd_name'=>'성남시'),
    array('erd_id'=>39,'er_id'=>2,'erd_name'=>'수원시'), array('erd_id'=>40,'er_id'=>2,'erd_name'=>'시흥시'),
    array('erd_id'=>41,'er_id'=>2,'erd_name'=>'안산시'), array('erd_id'=>42,'er_id'=>2,'erd_name'=>'안성시'),
    array('erd_id'=>43,'er_id'=>2,'erd_name'=>'안양시'), array('erd_id'=>44,'er_id'=>2,'erd_name'=>'양주시'),
    array('erd_id'=>45,'er_id'=>2,'erd_name'=>'양평군'), array('erd_id'=>46,'er_id'=>2,'erd_name'=>'여주시'),
    array('erd_id'=>47,'er_id'=>2,'erd_name'=>'연천군'), array('erd_id'=>48,'er_id'=>2,'erd_name'=>'오산시'),
    array('erd_id'=>49,'er_id'=>2,'erd_name'=>'용인시'), array('erd_id'=>50,'er_id'=>2,'erd_name'=>'의왕시'),
    array('erd_id'=>51,'er_id'=>2,'erd_name'=>'의정부시'), array('erd_id'=>52,'er_id'=>2,'erd_name'=>'이천시'),
    array('erd_id'=>53,'er_id'=>2,'erd_name'=>'파주시'), array('erd_id'=>54,'er_id'=>2,'erd_name'=>'평택시'),
    array('erd_id'=>55,'er_id'=>2,'erd_name'=>'포천시'), array('erd_id'=>56,'er_id'=>2,'erd_name'=>'하남시'),
    array('erd_id'=>57,'er_id'=>2,'erd_name'=>'화성시'),
    array('erd_id'=>58,'er_id'=>3,'erd_name'=>'강화군'), array('erd_id'=>59,'er_id'=>3,'erd_name'=>'계양구'),
    array('erd_id'=>60,'er_id'=>3,'erd_name'=>'남구'), array('erd_id'=>61,'er_id'=>3,'erd_name'=>'남동구'),
    array('erd_id'=>62,'er_id'=>3,'erd_name'=>'동구'), array('erd_id'=>63,'er_id'=>3,'erd_name'=>'미추홀구'),
    array('erd_id'=>64,'er_id'=>3,'erd_name'=>'부평구'), array('erd_id'=>65,'er_id'=>3,'erd_name'=>'서구'),
    array('erd_id'=>66,'er_id'=>3,'erd_name'=>'연수구'), array('erd_id'=>67,'er_id'=>3,'erd_name'=>'옹진군'),
    array('erd_id'=>68,'er_id'=>3,'erd_name'=>'중구'),
    array('erd_id'=>69,'er_id'=>4,'erd_name'=>'강서구'), array('erd_id'=>70,'er_id'=>4,'erd_name'=>'금정구'),
    array('erd_id'=>71,'er_id'=>4,'erd_name'=>'기장군'), array('erd_id'=>72,'er_id'=>4,'erd_name'=>'남구'),
    array('erd_id'=>73,'er_id'=>4,'erd_name'=>'동구'), array('erd_id'=>74,'er_id'=>4,'erd_name'=>'동래구'),
    array('erd_id'=>75,'er_id'=>4,'erd_name'=>'부산진구'), array('erd_id'=>76,'er_id'=>4,'erd_name'=>'북구'),
    array('erd_id'=>77,'er_id'=>4,'erd_name'=>'사상구'), array('erd_id'=>78,'er_id'=>4,'erd_name'=>'사하구'),
    array('erd_id'=>79,'er_id'=>4,'erd_name'=>'서구'), array('erd_id'=>80,'er_id'=>4,'erd_name'=>'수영구'),
    array('erd_id'=>81,'er_id'=>4,'erd_name'=>'연제구'), array('erd_id'=>82,'er_id'=>4,'erd_name'=>'영도구'),
    array('erd_id'=>83,'er_id'=>4,'erd_name'=>'중구'), array('erd_id'=>84,'er_id'=>4,'erd_name'=>'해운대구'),
    array('erd_id'=>85,'er_id'=>5,'erd_name'=>'남구'), array('erd_id'=>86,'er_id'=>5,'erd_name'=>'달서구'),
    array('erd_id'=>87,'er_id'=>5,'erd_name'=>'달성군'), array('erd_id'=>88,'er_id'=>5,'erd_name'=>'동구'),
    array('erd_id'=>89,'er_id'=>5,'erd_name'=>'북구'), array('erd_id'=>90,'er_id'=>5,'erd_name'=>'서구'),
    array('erd_id'=>91,'er_id'=>5,'erd_name'=>'수성구'), array('erd_id'=>92,'er_id'=>5,'erd_name'=>'중구'),
    array('erd_id'=>93,'er_id'=>6,'erd_name'=>'광산구'), array('erd_id'=>94,'er_id'=>6,'erd_name'=>'남구'),
    array('erd_id'=>95,'er_id'=>6,'erd_name'=>'동구'), array('erd_id'=>96,'er_id'=>6,'erd_name'=>'북구'),
    array('erd_id'=>97,'er_id'=>6,'erd_name'=>'서구'),
    array('erd_id'=>98,'er_id'=>7,'erd_name'=>'대덕구'), array('erd_id'=>99,'er_id'=>7,'erd_name'=>'동구'),
    array('erd_id'=>100,'er_id'=>7,'erd_name'=>'서구'), array('erd_id'=>101,'er_id'=>7,'erd_name'=>'유성구'),
    array('erd_id'=>102,'er_id'=>7,'erd_name'=>'중구'),
    array('erd_id'=>103,'er_id'=>8,'erd_name'=>'남구'), array('erd_id'=>104,'er_id'=>8,'erd_name'=>'동구'),
    array('erd_id'=>105,'er_id'=>8,'erd_name'=>'북구'), array('erd_id'=>106,'er_id'=>8,'erd_name'=>'울주군'),
    array('erd_id'=>107,'er_id'=>8,'erd_name'=>'중구'),
    array('erd_id'=>108,'er_id'=>9,'erd_name'=>'강릉시'), array('erd_id'=>109,'er_id'=>9,'erd_name'=>'고성군'),
    array('erd_id'=>110,'er_id'=>9,'erd_name'=>'동해시'), array('erd_id'=>111,'er_id'=>9,'erd_name'=>'삼척시'),
    array('erd_id'=>112,'er_id'=>9,'erd_name'=>'속초시'), array('erd_id'=>113,'er_id'=>9,'erd_name'=>'양구군'),
    array('erd_id'=>114,'er_id'=>9,'erd_name'=>'양양군'), array('erd_id'=>115,'er_id'=>9,'erd_name'=>'영월군'),
    array('erd_id'=>116,'er_id'=>9,'erd_name'=>'원주시'), array('erd_id'=>117,'er_id'=>9,'erd_name'=>'인제군'),
    array('erd_id'=>118,'er_id'=>9,'erd_name'=>'정선군'), array('erd_id'=>119,'er_id'=>9,'erd_name'=>'철원군'),
    array('erd_id'=>120,'er_id'=>9,'erd_name'=>'춘천시'), array('erd_id'=>121,'er_id'=>9,'erd_name'=>'태백시'),
    array('erd_id'=>122,'er_id'=>9,'erd_name'=>'평창군'), array('erd_id'=>123,'er_id'=>9,'erd_name'=>'홍천군'),
    array('erd_id'=>124,'er_id'=>9,'erd_name'=>'화천군'), array('erd_id'=>125,'er_id'=>9,'erd_name'=>'횡성군'),
    array('erd_id'=>126,'er_id'=>10,'erd_name'=>'거제시'), array('erd_id'=>127,'er_id'=>10,'erd_name'=>'거창군'),
    array('erd_id'=>128,'er_id'=>10,'erd_name'=>'고성군'), array('erd_id'=>129,'er_id'=>10,'erd_name'=>'남해시'),
    array('erd_id'=>130,'er_id'=>10,'erd_name'=>'남해군'), array('erd_id'=>131,'er_id'=>10,'erd_name'=>'밀양시'),
    array('erd_id'=>132,'er_id'=>10,'erd_name'=>'사천시'), array('erd_id'=>133,'er_id'=>10,'erd_name'=>'산청군'),
    array('erd_id'=>134,'er_id'=>10,'erd_name'=>'양산시'), array('erd_id'=>135,'er_id'=>10,'erd_name'=>'의령군'),
    array('erd_id'=>136,'er_id'=>10,'erd_name'=>'진주시'), array('erd_id'=>137,'er_id'=>10,'erd_name'=>'창녕군'),
    array('erd_id'=>138,'er_id'=>10,'erd_name'=>'창원시'), array('erd_id'=>139,'er_id'=>10,'erd_name'=>'통영시'),
    array('erd_id'=>140,'er_id'=>10,'erd_name'=>'하동군'), array('erd_id'=>141,'er_id'=>10,'erd_name'=>'함안군'),
    array('erd_id'=>142,'er_id'=>10,'erd_name'=>'함양군'), array('erd_id'=>143,'er_id'=>10,'erd_name'=>'합천군'),
    array('erd_id'=>144,'er_id'=>11,'erd_name'=>'경산시'), array('erd_id'=>145,'er_id'=>11,'erd_name'=>'경주시'),
    array('erd_id'=>146,'er_id'=>11,'erd_name'=>'고령군'), array('erd_id'=>147,'er_id'=>11,'erd_name'=>'구미시'),
    array('erd_id'=>148,'er_id'=>11,'erd_name'=>'군위군'), array('erd_id'=>149,'er_id'=>11,'erd_name'=>'김천시'),
    array('erd_id'=>150,'er_id'=>11,'erd_name'=>'문경시'), array('erd_id'=>151,'er_id'=>11,'erd_name'=>'봉화군'),
    array('erd_id'=>152,'er_id'=>11,'erd_name'=>'상주시'), array('erd_id'=>153,'er_id'=>11,'erd_name'=>'성주군'),
    array('erd_id'=>154,'er_id'=>11,'erd_name'=>'안동시'), array('erd_id'=>155,'er_id'=>11,'erd_name'=>'영덕군'),
    array('erd_id'=>156,'er_id'=>11,'erd_name'=>'영양군'), array('erd_id'=>157,'er_id'=>11,'erd_name'=>'영주시'),
    array('erd_id'=>158,'er_id'=>11,'erd_name'=>'영천시'), array('erd_id'=>159,'er_id'=>11,'erd_name'=>'예천군'),
    array('erd_id'=>160,'er_id'=>11,'erd_name'=>'울릉군'), array('erd_id'=>161,'er_id'=>11,'erd_name'=>'울진군'),
    array('erd_id'=>162,'er_id'=>11,'erd_name'=>'의성군'), array('erd_id'=>163,'er_id'=>11,'erd_name'=>'청도군'),
    array('erd_id'=>164,'er_id'=>11,'erd_name'=>'청송군'), array('erd_id'=>165,'er_id'=>11,'erd_name'=>'칠곡군'),
    array('erd_id'=>166,'er_id'=>11,'erd_name'=>'포항시'),
    array('erd_id'=>167,'er_id'=>12,'erd_name'=>'강진군'), array('erd_id'=>168,'er_id'=>12,'erd_name'=>'고흥군'),
    array('erd_id'=>169,'er_id'=>12,'erd_name'=>'곡성군'), array('erd_id'=>170,'er_id'=>12,'erd_name'=>'광양시'),
    array('erd_id'=>171,'er_id'=>12,'erd_name'=>'구례군'), array('erd_id'=>172,'er_id'=>12,'erd_name'=>'나주시'),
    array('erd_id'=>173,'er_id'=>12,'erd_name'=>'담양군'), array('erd_id'=>174,'er_id'=>12,'erd_name'=>'목포시'),
    array('erd_id'=>175,'er_id'=>12,'erd_name'=>'무안군'), array('erd_id'=>176,'er_id'=>12,'erd_name'=>'보성군'),
    array('erd_id'=>177,'er_id'=>12,'erd_name'=>'순천시'), array('erd_id'=>178,'er_id'=>12,'erd_name'=>'신안군'),
    array('erd_id'=>179,'er_id'=>12,'erd_name'=>'여수시'), array('erd_id'=>180,'er_id'=>12,'erd_name'=>'영광군'),
    array('erd_id'=>181,'er_id'=>12,'erd_name'=>'영암군'), array('erd_id'=>182,'er_id'=>12,'erd_name'=>'완도군'),
    array('erd_id'=>183,'er_id'=>12,'erd_name'=>'장성군'), array('erd_id'=>184,'er_id'=>12,'erd_name'=>'장흥군'),
    array('erd_id'=>185,'er_id'=>12,'erd_name'=>'진도군'), array('erd_id'=>186,'er_id'=>12,'erd_name'=>'함평군'),
    array('erd_id'=>187,'er_id'=>12,'erd_name'=>'해남군'), array('erd_id'=>188,'er_id'=>12,'erd_name'=>'화순군'),
    array('erd_id'=>189,'er_id'=>13,'erd_name'=>'고창군'), array('erd_id'=>190,'er_id'=>13,'erd_name'=>'군산시'),
    array('erd_id'=>191,'er_id'=>13,'erd_name'=>'김제시'), array('erd_id'=>192,'er_id'=>13,'erd_name'=>'남원시'),
    array('erd_id'=>193,'er_id'=>13,'erd_name'=>'무주군'), array('erd_id'=>194,'er_id'=>13,'erd_name'=>'부안군'),
    array('erd_id'=>195,'er_id'=>13,'erd_name'=>'순창군'), array('erd_id'=>196,'er_id'=>13,'erd_name'=>'완주군'),
    array('erd_id'=>197,'er_id'=>13,'erd_name'=>'익산시'), array('erd_id'=>198,'er_id'=>13,'erd_name'=>'임실군'),
    array('erd_id'=>199,'er_id'=>13,'erd_name'=>'장수군'), array('erd_id'=>200,'er_id'=>13,'erd_name'=>'전주시'),
    array('erd_id'=>201,'er_id'=>13,'erd_name'=>'정읍시'), array('erd_id'=>202,'er_id'=>13,'erd_name'=>'진안군'),
    array('erd_id'=>203,'er_id'=>14,'erd_name'=>'계룡시'), array('erd_id'=>204,'er_id'=>14,'erd_name'=>'공주시'),
    array('erd_id'=>205,'er_id'=>14,'erd_name'=>'금산군'), array('erd_id'=>206,'er_id'=>14,'erd_name'=>'논산시'),
    array('erd_id'=>207,'er_id'=>14,'erd_name'=>'당진시'), array('erd_id'=>208,'er_id'=>14,'erd_name'=>'보령시'),
    array('erd_id'=>209,'er_id'=>14,'erd_name'=>'부여군'), array('erd_id'=>210,'er_id'=>14,'erd_name'=>'서산시'),
    array('erd_id'=>211,'er_id'=>14,'erd_name'=>'서천군'), array('erd_id'=>212,'er_id'=>14,'erd_name'=>'아산시'),
    array('erd_id'=>213,'er_id'=>14,'erd_name'=>'예산군'), array('erd_id'=>214,'er_id'=>14,'erd_name'=>'천안시'),
    array('erd_id'=>215,'er_id'=>14,'erd_name'=>'청양군'), array('erd_id'=>216,'er_id'=>14,'erd_name'=>'태안군'),
    array('erd_id'=>217,'er_id'=>14,'erd_name'=>'홍성군'),
    array('erd_id'=>218,'er_id'=>15,'erd_name'=>'괴산군'), array('erd_id'=>219,'er_id'=>15,'erd_name'=>'단양군'),
    array('erd_id'=>220,'er_id'=>15,'erd_name'=>'보은군'), array('erd_id'=>221,'er_id'=>15,'erd_name'=>'영동군'),
    array('erd_id'=>222,'er_id'=>15,'erd_name'=>'옥천군'), array('erd_id'=>223,'er_id'=>15,'erd_name'=>'음성군'),
    array('erd_id'=>224,'er_id'=>15,'erd_name'=>'제천시'), array('erd_id'=>225,'er_id'=>15,'erd_name'=>'증평군'),
    array('erd_id'=>226,'er_id'=>15,'erd_name'=>'진천군'), array('erd_id'=>227,'er_id'=>15,'erd_name'=>'청원군'),
    array('erd_id'=>228,'er_id'=>15,'erd_name'=>'청주시'), array('erd_id'=>229,'er_id'=>15,'erd_name'=>'충주시'),
    array('erd_id'=>230,'er_id'=>16,'erd_name'=>'세종시'),
    array('erd_id'=>231,'er_id'=>17,'erd_name'=>'서귀포시'), array('erd_id'=>232,'er_id'=>17,'erd_name'=>'제주시'));
